cc_library(
    name = "timer",
    srcs = ["timer.c"],
    hdrs = ["timer.h"],
    visibility = ["//main:__pkg__"]
)

cc_library(
    name = "random",
    srcs = ["random.c"],
    hdrs = ["random.h"],
    visibility = ["//main:__pkg__"]
)
